apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api-deployment
  labels:
    app: server-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-api
  template:
    metadata:
      labels:
        app: server-api
    spec:
      containers:
      - name: server-api
        image: server-api-image:v1
        ports:
        - containerPort: 3001