version: '3.3'

services:
  postgres:
    container_name: sdc_products
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: student
      POSTGRES_DB: sdc
    image: postgres:11.5
    expose:
      - 5433
    ports:
      - 5432:5432
    volumes:
      - ./SDCDATA.sql:/docker-entrypoint-initdb.d/SDCDATA.sql
  app:
    container_name: sdc_server
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: sdc_products
      DB_USER: postgres
      DB_PASS: student
      DB_DB: sdc
      NODE_ENV: development
      # PORT: 3000
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

# volumes:
#   pgdata:
#     external: true
#     name:
#       product_vol

  